security:
    encoders:
        App\Entity\User:
#permet de crypter les mot de passe
            algorithm: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#les utilisateurs de la class entity User
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
#le parfeu, dev: permet d'avoir les permissions pour coder main: permet à tout utilisateur d'accéder au site
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
#la vérification du formulaire login par rapport au nom du loginController
            form_login:
                login_path: app_login
                check_path: app_login

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
#permet de choisir une route pour la déconnexion
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
